# Random Number Generation with NumPy

This notebook covers generating NumPy arrays of random numbers using its random number generator (`default_rng`). This allows us to perform simulations and practice some of the techniques we've learned so far on NumPy arrays.

## Setup

Import NumPy as its accepted alias, `np`.

In [1]:
import numpy as np

## Initializing a random number generator

So far, we've used `np.random` called multiple times to create lists or arrays of random numbers. For more control and functionality, we can create a random number generator object to be used multiple times. This random number generator can be created with a random seed to ensure that every time you run your notebook, you get the same random numbers.
This is useful for reproducibility.

In [2]:
# Create a random generator with a seed
rg = np.random.default_rng(seed=2100)
rg

Generator(PCG64) at 0x17E0E949540

### Generating a 1D Array of Random Integers

We can generate a 1-dimensional array of random integers between two values.

In [3]:
# Generate 10 random integers from 1 to 10
arr_1d = rg.integers(1, 11, size=10) # note that the second argument is an exclusive stop as is typical in Python
arr_1d

array([10,  3,  9, 10,  7,  3,  2,  6,  3,  1], dtype=int64)

## Generating a 2D Array of Random Numbers

We can also generate 2-dimensional arrays of random floats between 0 and 1 using random(). These are sampled from a uniform distribution.

In [5]:
# Generate a 4 x 5 array of random floats(between 0 and 1)
arr2d = rg.random((4, 5))
print(arr2d.shape)
arr2d

(4, 5)


array([[0.1406208 , 0.66198709, 0.71768881, 0.72701141, 0.85859247],
       [0.33080681, 0.35247246, 0.01734227, 0.20309907, 0.03787868],
       [0.41570194, 0.97584326, 0.51151819, 0.99320582, 0.75986868],
       [0.95971452, 0.34403374, 0.70244883, 0.49446014, 0.54310404]])

In [6]:
#Generate a 4 x 5 array of integers from 2 to 15
arr = rg.integers(low=2, high=16, size=(4, 5))
arr

array([[13,  9,  2,  8,  9],
       [ 2,  9,  8, 10,  6],
       [12,  9,  5, 15,  4],
       [ 4, 13,  9,  8,  7]], dtype=int64)

## Generating a NumPy array of random numbers from a Gaussian distribution

With NumPy's random number generator, you can also sample from distributions other than uniform. To generate random numbers from a Gaussian, we can use the `normal` method of NumPy's random number generator. Here's the syntax:

```python
<random_number_generator>.normal(<mean>, <std>, shape)
```

You must specify the mean and the standard deviation of the Gaussian (normal) distribution you're sampling from, as well as the return shape `(<rows>, <columns>)` you'd like.

Let's demonstrate sampling an array of 3 rows and 5 columns with random numbers sampled according to a Gaussian distribution with 0 mean and standard deviation of 1.

In [7]:
gaussian_2d = rg.normal(0, 1, (3,5))
gaussian_2d

array([[-0.58723019, -0.49805831, -1.81332966,  0.44988513, -0.04786059],
       [ 0.98783026,  0.12860523,  1.20120203,  1.31725527,  1.07242078],
       [ 0.28528642, -0.68455276,  1.0638172 ,  1.69322948, -0.04202962]])

# Practice Exercise 1

1. Repeat a random experiment twice using the same seed — confirm the results match.

In [12]:
rg = np.random.default_rng(seed=1100)
gaussian_1 = rg.normal(1, 2, (2,3))
gaussian_1


array([[-0.01756169,  2.77911232,  3.13818063],
       [ 1.10296334, -2.02721217,  1.99861765]])

In [13]:
rg = np.random.default_rng(seed=1100)
gaussian_2 = rg.normal(1, 2, (2,3))
gaussian_2

array([[-0.01756169,  2.77911232,  3.13818063],
       [ 1.10296334, -2.02721217,  1.99861765]])

# Practice Exercise 2

Generate a 1D array of 20 random integers between 50 and 100.

In [14]:
arr_1d = rg.integers(50, 100, size=20) 
arr_1d

array([61, 64, 54, 63, 79, 56, 94, 82, 81, 74, 86, 84, 88, 96, 73, 50, 69,
       64, 77, 52], dtype=int64)

# Practic Exercise 3

Generate two 1D arrays of random integers and concatenate them. (Hint: Use previous notebooks for reference for concatenate)

In [15]:
arr_1 = rg.integers(1, 10, size=5)
arr_1

array([8, 5, 2, 3, 3], dtype=int64)

In [16]:
arr_2 = rg.integers(1, 10, size=5)
arr_2

array([6, 9, 1, 6, 4], dtype=int64)

In [17]:
conc = np.concatenate([arr_1, arr_2])
conc

array([8, 5, 2, 3, 3, 6, 9, 1, 6, 4], dtype=int64)