# Reshaping, Flattening, and Transposing NumPy Arrays

NumPy makes it easy to reshape and reorganize arrays without changing the total number of elements.  
This notebook covers:

- Converting 1D arrays into 2D with `.reshape()`
- Understanding `.size` and shape constraints
- Transposing arrays with `.T`
- Flattening arrays with `.ravel()` and `.squeeze()`


## Setup

Import numpy with its commonly accepted alias, `np`.

In [1]:
import numpy as np

## Reshaping a 1D Array Into 2D

We use `.reshape(rows, columns)` to convert a 1D array into a 2D array with the new number of rows and columns specified as arguments to `reshape()`.

Note: The number of rows × number of columns must equal the total number of elements (`.size`) in the original array.

In [2]:
#Initialize an 1D array with 12 elements
arr = np.arange(12)
print(arr.size)
arr

12


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### ✔️ Reshape into 3 rows × 4 columns

In [3]:
arr2d = arr.reshape(3, 4)
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

What happens if you try to reshape to a shape that doesn't match the total number of elements in the original array?

In [4]:
arr2d = arr.reshape(3, 2)
arr2d

ValueError: cannot reshape array of size 12 into shape (3,2)

It's unclear how NumPy should resize an array of 12 elements into a shape that only permits 6 elements.

## Using `-1` to Avoid Mental Math

NumPy can automatically compute one of the dimensions using `-1`.

You only specify one dimension and NumPy figures out the other! This can be very helpful.


In [5]:
arr.reshape(2, -1)    # NumPy finds number of columns, (12/2)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

## Transposing a 2D Array

The `.T` attribute flips the array:

- Rows ↔ Columns
- Shape becomes `(columns, rows)`


In [6]:
print("The original array shape is, ", arr2d.shape)
print(arr2d.T)
print("The transposed array shape is", arr2d.T.shape)

The original array shape is,  (3, 4)
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
The transposed array shape is (4, 3)


## Reshaping Can Produce a 2D Array With One Row

Example:

In [7]:
arr.reshape(1, 12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

### How do we know it's 2D? - Count the brackets

At first glance, converting a 1D array into a 2D array with a single row (e.g., shape `(1, n)`) might feel redundant, but it is very useful in some matrix operations where there is a need for exactly 1 row or 1 column.

In [8]:
arr10_2d = np.arange(10).reshape(1,10)
arr10_2d

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [9]:
arr10_transpose = arr10_2d.reshape(10, -1); #it will convert 1 x 10 to 10 x 1
print(arr10_2d)
print(arr10_transpose)

[[0 1 2 3 4 5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


## Flattening a 2D Array Back to 1D

### Option 1: `.ravel()`  
Note that any changes made will affect the original array, so it's best to run `.ravel().copy()` for a new copy fo the array.

In [10]:
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
flat_ravel = arr2d.ravel()
print(flat_ravel)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


### Option 2: `.squeeze()`  
Removes dimensions of size 1 (e.g., `(1, 12)` → `(12,)`). This will not necessarily return a 1D array.

In [12]:
flat_squeeze = arr2d.reshape(1, 12).squeeze()
flat_squeeze

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
flat_attempt = arr2d.reshape(3, 4).squeeze(); # If one of the dimensions is not 1, it will return the original array.
print(flat_attempt)

# Practice Exercise 1

1. Create a 1D array of size 15 and reshape it into:
   - a 3×5 array  
   - a 5×3 array using `-1`

In [ ]:
arr_1 = np.arange(15).reshape(3, 5)
arr_1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
arr_1 = np.arange(15).reshape(3, -1)
arr_1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# Practice Exercise 2

Given a 2×6 array, transpose it and flatten it using `.squeeze()`.

In [21]:
sample_arr = [
    [4,6,3,2,7,4],
    [5,4,8,9,9,1]
]
arr = np.array(sample_arr)
arr

array([[4, 6, 3, 2, 7, 4],
       [5, 4, 8, 9, 9, 1]])

In [23]:
flat_squeeze = arr2d.reshape(2, 6).squeeze()
flat_squeeze

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])