# 1-dimensional (1D) NumPy arrays

In [1]:
import numpy as np

## Creating an example 1D array

In [4]:
arr6 = np.arange(6)
arr6

array([0, 1, 2, 3, 4, 5])

In [5]:
type(arr6)

numpy.ndarray

## Slicing and indexing 1D arrays

In [8]:
arr6[-1]

5

In [9]:
arr6[:3]

array([0, 1, 2])

In [10]:
arr6[3:]

array([3, 4, 5])

## NumPy array attributes

In [11]:
arr6.ndim # number of dimensions

1

In [12]:
arr6.shape

(6,)

In [13]:
type(arr6.shape)

tuple

<strong>Tuple</strong> is an ordered, immutable collection of items, meaning its elements cannot be changed after its creation. 

In [14]:
arr6.size

6

## Creating 1D NumPy arrays

You can create NumPy arrays from lists

In [15]:
arr = np.array([3, 3, 5, 9])
arr

array([3, 3, 5, 9])

There are specialty functions for creating arrays of all the same value

In [17]:
all_zeros = np.zeros(5)
all_zeros

array([0., 0., 0., 0., 0.])

In [18]:
all_ones = np.ones(5)
all_ones

array([1., 1., 1., 1., 1.])

The `np.arange()` function has 3 arguments: `(<start>, <stop_exclusive>, <step>)`

In [19]:
evens = np.arange(0, 10, 2)
evens

array([0, 2, 4, 6, 8])

In [20]:
np.arange(0, 10+1, 2)

array([ 0,  2,  4,  6,  8, 10])

`np.linspace()` is similar to `np.arange()`, but takes different arguments:  
`(<start>, <stop_inclusive>, <number_of_points>)`

In [21]:
np.linspace(1, 100, num=100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [22]:
np.linspace(0, 1, num=50+1)

array([0.  , 0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 ,
       0.22, 0.24, 0.26, 0.28, 0.3 , 0.32, 0.34, 0.36, 0.38, 0.4 , 0.42,
       0.44, 0.46, 0.48, 0.5 , 0.52, 0.54, 0.56, 0.58, 0.6 , 0.62, 0.64,
       0.66, 0.68, 0.7 , 0.72, 0.74, 0.76, 0.78, 0.8 , 0.82, 0.84, 0.86,
       0.88, 0.9 , 0.92, 0.94, 0.96, 0.98, 1.  ])

## Testing for equality and adding arrays together
Note that this is different than Python lists

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros(5) == np.zeros(5)

array([ True,  True,  True,  True,  True])

In [25]:
np.array_equal(np.zeros(5), np.zeros(5))

True

In [27]:
[1,2] + [1,2]

[1, 2, 1, 2]

In [28]:
np.array([1, 2]) + np.array([1, 2])

array([2, 4])