# 2-dimensional (2D) NumPy arrays

In [1]:
import numpy as np

## Creating 2D NumPy arrays from lists of lists

In [3]:
list_of_lists = [
    [1, 'apple', 25],
    [2, 'banana', 36]
]
print(len(list_of_lists[0]))

3


In [4]:
arr2d = np.array(list_of_lists)

In [6]:
arr2d.ndim

2

In [7]:
arr2d.shape

(2, 3)

## Creating 2D arrays from 1D arrays

In [8]:
all_zeros = np.zeros(5)
all_ones = np.ones(5)

In [9]:
vstacked = np.vstack([all_zeros, all_ones])
vstacked

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [10]:
vstacked.shape

(2, 5)

We can "stack" the 1D arrays vertically on top of each other with `np.vstack()`

<img src="attachment:15639138-5df5-4e60-8cbb-a42b49e2c6fb.png" style="width:150px;"/>

## Slicing and indexing 2D NumPy arrays

In [11]:
my_2d = np.array(
    [[0,0,0],
     [1,1,1],
     [2,2,2],
     [3,3,3]]
)
my_2d

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

The syntax for slicing and indexing 2D NumPy arrays is `array[<row_index>, <column_index>]`  
You can use `:` to mean "all rows" or "all columns"

In [12]:
my_2d[0, :] # row 0, all columns

array([0, 0, 0])

In [13]:
my_2d[-1, :]

array([3, 3, 3])

In [14]:
my_2d.size

12

In [ ]:
my_2d[1, 2]

1

In [17]:
my_2d[:2, :] # first 2 rows, all columns

array([[0, 0, 0],
       [1, 1, 1]])

In [18]:
my_2d[:3, 1:] # first 3 rows, columns starting at column 1

array([[0, 0],
       [1, 1],
       [2, 2]])